services:
  postgres:
    image: postgres:17
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../../cache/pgdata:/var/lib/postgresql/data
